<?php

return [
    '6801' => 'Request for Sending SMS is success (not meaning sending sms itself is success)',
    '6810' => 'Incomplete Parameter',
    '6811' => 'Illegal username character',
    '6812' => 'Password not valid',
    '6813' => 'Illegal MSISDN character',
    '6814' => 'Illegal Message / Message not exist',
    '6815' => 'Illegal Sender character',
    '6816' => 'Invalid Message Type',
    '6818' => 'OTP contained message forbidden for non-otp route',
    '6831' => 'Username Not Exist',
    '6832' => 'Client Ip Address Access Denied',
    '6833' => 'Wrong Password',
    '6834' => 'No Sender Access',
    '6835' => 'No Company Data',
    '6836' => 'No Route Detected',
    '6837' => 'No Deal Detected',
    '6838' => 'No Operator Detected',
    '6839' => 'Sender Param Not Found',
    '6841' => 'Error Commit Billing (Issue Internal #1)',
    '6842' => 'Error Commit Billing (Issue Internal #2)',
    '6843' => 'Error Commit Billing (Issue Internal #3)',
    '6844' => 'Error Commit Billing (Not Enough Prepaid Quota)',
    '6851' => 'Error Sending SMS',
    '6852' => 'Internal Server Fault',
    '3700' => 'Sent To Telco without DLR',
    '3701' => 'Sent To Telco and Delivery report Received',
    '3703' => 'Invalid MSISDN',
    '3704' => 'Failed to send to telco, Integration Issue',
    '3710' => 'Failed to send to telco, Connection Timed Out',
    '3711' => 'SMS sent to Telco but No Delivery Report Received (DLR Timed out)',
    '3712' => 'SMS sent To Telco and Delivery Report From Telco = UNDELIVERED',
    '3713' => 'SMS sent To Telco and Delivery Report From Telco = MSISDN Not',
    '3788' => 'Found/Unknown/Not Registered',
    'list_success_final_status_code' => [3700, 3701, 3711, 3712, 3713],
];
